# frozen_string_literal: true

require_relative 'idoklad_client/constants'
require_relative 'idoklad_client/enums'
require_relative 'idoklad_client/schema'
require_relative 'idoklad_client/case_converter'
require_relative 'idoklad_client/endpoints/base'
require_relative 'idoklad_client/endpoints/contacts'
require_relative 'idoklad_client/endpoints/webhooks'
require_relative 'idoklad_client/endpoints/issued_invoices'
require_relative 'idoklad_client/endpoints/proforma_invoices'
require_relative 'idoklad_client/endpoints/received_invoices'
require_relative 'idoklad_client/endpoints/credit_notes'
require_relative 'idoklad_client/endpoints/sales_receipts'
require_relative 'idoklad_client/endpoints/bank_accounts'
require_relative 'idoklad_client/endpoints/bank_statements'
require_relative 'idoklad_client/endpoints/price_list_items'
require_relative 'idoklad_client/endpoints/numeric_sequences'
require_relative 'idoklad_client/client'
require_relative 'idoklad_client/configuration'
